"""."""

import os
import tempfile

import pytest
from DIRACCommon.Core.Utilities.ReturnValues import S_OK
from pytest_mock import MockerFixture

from dirac_cwl_proto.commands import UploadLogFile


class TestUploadLogFile:
    """Collection of tests for the UploadLogFile command."""

    FILENAMES = ["file.txt", "file.log", "file.err", "file.out", "file.extra"]
    JOB_ID = "8042"
    PRODUCTION_ID = "95376"
    NAMESPACE = "MC"
    CONFIG_VERSION = "2016"

    @pytest.fixture
    def basedir(self):
        """Fixture to initialize the working directory."""
        with tempfile.TemporaryDirectory() as tmpdir:
            for file in self.FILENAMES:
                with open(os.path.join(tmpdir, file), "x") as f:
                    f.write("EMPTY")

            yield tmpdir

    def test_upload_ok(self, basedir, mocker: MockerFixture):
        """Test a correct upload."""
        base_lfn = f"/lhcb/{self.NAMESPACE}/{self.CONFIG_VERSION}/LOG/{self.PRODUCTION_ID.zfill(8)}/0000/"
        zip_name = self.JOB_ID.zfill(8) + ".zip"

        expected_lfn = os.path.join(base_lfn, zip_name)
        expected_zip = os.path.join(basedir, zip_name)

        mock_put = mocker.patch("dirac_cwl_proto.data_management_mocks.data_manager.MockDataManager.put")
        mock_putAndRegister = mocker.patch(
            "dirac_cwl_proto.data_management_mocks.data_manager.MockDataManager.putAndRegister",
        )

        mock_put.return_value = S_OK({"Successful": {expected_lfn: "OKAY"}, "Failed": {}})

        result = UploadLogFile().execute(
            basedir,
            job_id=self.JOB_ID,
            production_id=self.PRODUCTION_ID,
            namespace=self.NAMESPACE,
            config_version=self.CONFIG_VERSION,
        )

        mock_put.assert_called_once_with(expected_lfn, expected_zip, "LogSE")
        mock_putAndRegister.assert_not_called()
        assert result["OK"]

    def test_upload_ok_to_failover(self, basedir, mocker: MockerFixture):
        """Test a failure to upload to the LogSE but a correct one to the Failover."""
        base_lfn = f"/lhcb/{self.NAMESPACE}/{self.CONFIG_VERSION}/LOG/{self.PRODUCTION_ID.zfill(8)}/0000/"
        zip_name = self.JOB_ID.zfill(8) + ".zip"

        expected_lfn = os.path.join(base_lfn, zip_name)
        expected_zip = os.path.join(basedir, zip_name)

        mock_put = mocker.patch("dirac_cwl_proto.data_management_mocks.data_manager.MockDataManager.put")
        mock_putAndRegister = mocker.patch(
            "dirac_cwl_proto.data_management_mocks.data_manager.MockDataManager.putAndRegister",
        )

        mock_put.return_value = S_OK({"Successful": {}, "Failed": {expected_lfn: "Borked"}})
        mock_putAndRegister.return_value = S_OK({"Successful": {expected_lfn: "OKAY"}, "Failed": {}})

        result = UploadLogFile().execute(
            basedir,
            job_id=self.JOB_ID,
            production_id=self.PRODUCTION_ID,
            namespace=self.NAMESPACE,
            config_version=self.CONFIG_VERSION,
        )

        mock_put.assert_called_once_with(expected_lfn, expected_zip, "LogSE")
        mock_putAndRegister.assert_called_once_with(expected_lfn, expected_zip, "Tier1-Failover")
        assert result["OK"]

    def test_upload_fail(self, basedir, mocker: MockerFixture):
        """Test both a failure to LogSE and the FailoverSE."""
        base_lfn = f"/lhcb/{self.NAMESPACE}/{self.CONFIG_VERSION}/LOG/{self.PRODUCTION_ID.zfill(8)}/0000/"
        zip_name = self.JOB_ID.zfill(8) + ".zip"

        expected_lfn = os.path.join(base_lfn, zip_name)

        mock_put = mocker.patch("dirac_cwl_proto.data_management_mocks.data_manager.MockDataManager.put")
        mock_putAndRegister = mocker.patch(
            "dirac_cwl_proto.data_management_mocks.data_manager.MockDataManager.putAndRegister",
        )

        mock_put.return_value = S_OK({"Successful": {}, "Failed": {expected_lfn: "Borked"}})
        mock_putAndRegister.return_value = S_OK({"Successful": {}, "Failed": {expected_lfn: "Borked"}})

        result = UploadLogFile().execute(
            basedir,
            job_id=self.JOB_ID,
            production_id=self.PRODUCTION_ID,
            namespace=self.NAMESPACE,
            config_version=self.CONFIG_VERSION,
        )

        assert not result["OK"]

    # TO TEST: Failed to zip files - No outputs generated by the job
